# Generated by Django 5.2.4 on 2025-07-05 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Volume de Estoque')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Imagem Principal')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefone (WhatsApp)')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('customer_cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('customer_neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('customer_address', models.CharField(max_length=255, verbose_name='Endereço (Rua e Número)')),
                ('customer_reference', models.TextField(blank=True, null=True, verbose_name='Referência / Complemento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('status', models.CharField(choices=[('Novo', 'Novo'), ('Finalizado', 'Finalizado')], default='Novo', max_length=20, verbose_name='Status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='Produto Pedido')),
            ],
        ),
    ]
